name: "Acme.sh for Home Assistant"
version: "1.0.0"
slug: "acme_sh"
description: "ACME client to generate and renew SSL Certificates"
arch:
  - aarch64
  - amd64
url: "https://github.com/kheimon/homeassistant-acme"
map:
  - type: ssl
    read_only: False
boot: manual
startup: once
options:
  accountemail: null
  domain: null
  dnsapi: null
  dnsEnvVariables: []
  fullchainfile: fullchain.pem
  keyfile: privkey.pem
schema:
  accountemail: str
  domain: str
  dnsapi: str
  caserver: str?
  dnsEnvVariables:
    - name: str
      value: str
  keylength: match(2048|3072|4096|8192|ec-256|ec-384|ec-521)?
  fullchainfile: str
  keyfile: str
